@SieuThiService_HostAddress = http://localhost:5291

GET {{SieuThiService_HostAddress}}/weatherforecast/
Accept: application/json

###

### Lấy đơn hàng theo mã siêu thị
GET {{SieuThiService_HostAddress}}/api/DonHangSieuThi/sieu-thi/1
Accept: application/json
